# Generated by Django 5.2.4 on 2025-08-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oquv_markaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('number_of_teacher', models.DecimalField(decimal_places=0, max_digits=6)),
                ('number_of_students', models.DecimalField(decimal_places=0, max_digits=6)),
                ('desc', models.TextField()),
            ],
        ),
    ]
